# Generated by Django 6.0.7 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WifiNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("wifipassword", models.CharField(blank=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WPA", "WPA"),
                            ("WEP", "WEP"),
                            ("nopass", "No password"),
                        ],
                        default="WPA",
                        max_length=10,
                    ),
                ),
            ],
            options={"ordering": ("name",)},
        ),
    ]
