# Generated by Django 6.0.7 on 2026-07-15 16:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('lesson', 'Lesson'), ('video', 'Video'), ('document', 'Document'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('scorm', 'SCORM'), ('external_link', 'External link')], max_length=20)),
                ('position', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('completion_mode', models.CharField(choices=[('manual', 'Manual'), ('view', 'View'), ('progress', 'Progress'), ('score', 'Score')], default='manual', max_length=20)),
                ('minimum_progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minimum_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='ActivityResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('html', 'HTML'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('image', 'Image'), ('file', 'File'), ('url', 'URL')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_resources/')),
                ('external_url', models.URLField(blank=True)),
                ('launch_path', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.learningactivity')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.coursemodule')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='learningactivity',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.learningunit'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='unique_module_position_per_course'),
        ),
        migrations.AddConstraint(
            model_name='activityresource',
            constraint=models.UniqueConstraint(fields=('activity', 'position'), name='unique_resource_position_per_activity'),
        ),
        migrations.AddConstraint(
            model_name='learningunit',
            constraint=models.UniqueConstraint(fields=('module', 'position'), name='unique_unit_position_per_module'),
        ),
        migrations.AddConstraint(
            model_name='learningactivity',
            constraint=models.UniqueConstraint(fields=('unit', 'position'), name='unique_activity_position_per_unit'),
        ),
    ]
